# Dependencies
markdown:         redcarpet
highlights:       pygments

# Permalinks
permalink:        pretty

# Setup
title:            Sarah Kendrew
tagline:          European Space Agency
description:      European Space Agency
url:              http://skendrew.github.io
baseurl:          /

author:
  name:           'Sarah Kendrew'
  url:            https://twitter.com/sarahkendrew


# Where things are
source:             .
layouts:            /_layouts


# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
