# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Sarah Kendrew
tagline:          University of Oxford
description:      University of Oxford
url:              http://skendrew.github.io
baseurl:          /

author:
  name:           'Sarah Kendrew'
  url:            https://twitter.com/sarahkendrew

paginate:         5

# Where things are
#source:             .
#layouts:            /_layouts

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
